### ISSUE TITLE
Consider _1 % &X::m

### ISSUE THREAD

**Issue by pdimov** [pdimov/lambda2#5]
E.g. https://godbolt.org/z/9cfYqj3j7

**Comment by huangqinjin** [comment]
Isn't `_1 ->* &X::m` more expressive?

**Comment by pdimov** [comment]
`->*` works too; I'll think about it some more. https://godbolt.org/z/4x8PMTGWs

**Comment by pdimov** [comment]
`first`/`second` specifically can also be made members of `_1`, so that the more straightforward `_1.first` and `_1.second` works, e.g. https://godbolt.org/z/d8ejbxMfP. But `_1->*first` is user-extensible to other identifiers, whereas `_1.first` is not.

**Comment by beojan** [comment]
Wouldn't it need to be `_1->*&std::pair<T1, T2>::first`?

Would it be possible to provide free functions like `get` (maybe even both the index and type (used by `std::variant`) versions) and `at` (forwarding to the `at` member function)? Then the macros used for this could be used to provide other functions like those in `cmath` and the user could define "lifted" (stealing some terminology from Boost::HOF) versions of any function they like.

That said, I definitely prefer `->*` over `%` since I can see lambdas like `_1 % 2 == 0` not being uncommon.
